// <auto-generated />
namespace Romofyi.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _9initialcommit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_9initialcommit));
        
        string IMigrationMetadata.Id
        {
            get { return "202405230541486_9initialcommit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
